name: Master Release CI

on:
  workflow_dispatch:
    inputs:

      baseUrl:
        description: 'Maps Api Key'
        required: true
        default: 'AIzaSyBUezM-zpmz1egGJF5a6RC5Kh3gbgDZbJA'
  push:
    branches:
      - 'main'
      - 'release*'

# Um workflow é composto de um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este workflow contém um único job chamado "build-and-deploy"
  build-and-deploy:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest
    # Steps representam a sequência de tarefas usando shell runners que serão executadas como parte do job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Step para instalar o JDK
      - name: Set up JDK 11.0.15
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.15
      # Step para instalar o NDK
      - name: Install NDK
        run: echo "y" | /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570"
      - name: Grant permission to gradlew
        run: chmod +x ./gradlew
      - name: Build debug APK
        env:
          MAPS_API_KEY: ${{ github.event.inputs.mapKey }}
        run: ./gradlew assembleDebug -PmapsApiKey=${{ env.MAPS_API_KEY }}
